name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Build + Test
        run: |
          mvn -B clean test

      - name: Upload JUnit Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml

  quality:
    name: Quality Analysis
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Run Quality Reports
        run: |
          mvn -B verify jacoco:report checkstyle:checkstyle pmd:pmd spotbugs:spotbugs

      - name: Upload Quality Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            target/checkstyle-result.xml
            target/pmd.xml
            target/cpd.xml
            target/spotbugsXml.xml
            target/site/**

  security:
    name: Security Scans
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

    #   - name: Snyk Scan
    #     uses: snyk/actions@master
    #     with:
    #       command: test
    #     env:
    #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    #   - name: OWASP Dependency Check
    #     env:
    #         NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    #     run: |
    #         mvn -B verify

    #   - name: Upload Security Reports
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: security-reports
    #       path: |
    #         target/dependency-check-report.html
    #         target/dependency-check-report.xml

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: security

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Cache SonarQube Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: SonarQube Scan + Quality Gate
        run: |
            mvn clean verify sonar:sonar \
            -Dsonar.projectKey=demo-app \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN            
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}