name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-cache

      - name: Build + Test
        run: |
          mvn clean verify

      - name: Static Analysis
        run: |
          mvn jacoco:report \
          checkstyle:checkstyle \
          pmd:pmd \
          spotbugs:spotbugs

      - name: Snyk Security Dependency Scan
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: OWASP Dependency Security Scan
        run: |
          mvn org.owasp:dependency-check-maven:check \
          -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
          -Dsonar.projectKey=demo-app \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN